countries_list = [
    ('US', 'USA'),
    ('AF', 'Afghanistan'),
    ('AR', 'Argentina'),
    ('AU', 'Australia'),
    ('AT', 'Austria'),
    ('BE', 'Belgium'),
    ('BR', 'Brazil'),
    ('KH', 'Cambodia'),
    ('CA', 'Canada'),
    ('CZ', 'Czech Republic'),
    ('EG', 'Egypt'),
    ('SV', 'El Salvador'),
    ('FI', 'Finland'),
    ('FR', 'France'),
    ('DE', 'Germany'),
    ('IN', 'India'),
    ('IT', 'Italy'),
    ('JP', 'Japan'),
    ('KR', 'Korea (South)'),
    ('MX', 'Mexico'),
    ('NE', 'Niger'),
    ('PL', 'Poland'),
    ('RU', 'Russian Federation'),
    ('ES', 'Spain'),
    ('TW', 'Taiwan'),
    ('TR', 'Turkey'),
    ('UA', 'Ukraine'),
    ('UK', 'United Kingdom')
]